### ISSUE TITLE
Error loading settings

### ISSUE THREAD

**Issue by mzaur** [Drewster727/goes-notify#5]
python goes-notify.py
INFO: 04/29/2018 07:56:29 PM config file is:/config.json
ERROR: 04/29/2018 07:56:29 PM Error loading settings from config.json file: [Errno 2] No such file or directory: '/config.json'

Not sure what I am doing wrong? I am on Windows and installed python 2.7. I renamed config.json.example to config.json but it's not finding it for some reason?

**Comment by spacenikki** [comment]
The issue is fixed when I did below:
1. Go to goes-notify.py, line 185
2. At line 185, find --> default='%s/config.json'  
3. Delete "/" 
4. Now it should look like this - default='%sconfig.json'

**Comment by mzaur** [comment]
Thanks! That seems to have worked. I can run the script but then it just stops and i'm not sure why. Any idea? 

python goes-notify.py
INFO: 04/30/2018 10:16:13 PM config file is:config.json
DEBUG: 04/30/2018 10:16:13 PM Running cron with arguments: {'no_email': False, 'configfile': 'config.json', 'use_gmail': True}
DEBUG: 04/30/2018 10:16:13 PM Starting new HTTPS connection (1): ttp.cbp.dhs.gov
DEBUG: 04/30/2018 10:16:14 PM https://ttp.cbp.dhs.gov:443 "GET /schedulerapi/slots?orderBy=soonest&limit=3&locationId=7960&minimum=1 HTTP/1.1" 200 None

**Comment by mzaur** [comment]
or is this how it's supposed to be? The script just runs and then stops? I thought it would just keep running and checking every X minutes

**Comment by mzaur** [comment]
ok nevermind, I figured out how to run the script in powershell so that it repeats every 5 minutes

while(1)
{
    python goes-notify.py --use-gmail
    Start-Sleep -s 300
}
