### ISSUE TITLE
Why does the script not run when the hash text file is created?

### ISSUE THREAD

**Issue by radianrad** [Drewster727/goes-notify#6]
The text file that is created upon successfully finding a sooner time prevent the script from running again. Is this only if it's the same appointments?

**Comment by Drewster727** [comment]
https://github.com/Drewster727/goes-notify/blob/85fcf986206a205e27cecc158da139315f49412e/goes-notify.py#L129-L132

This prevents additional notifications when the same available dates are found.

It basically takes all of the "better" available dates and your current interview date (which you set in the config file) and creates a unique hash code. If any of those items changes on subsequent runs, you will get notified (assuming the available dates are better than your current interview date).

Does that make sense?

**Comment by radianrad** [comment]
Makes total sense! Neat solution.

Thanks!
