### ISSUE TITLE
Add NEXUS location codes

### ISSUE THREAD

**Issue by tjd2002** [Drewster727/goes-notify#7]
In many cases, NEXUS appointments at a given location use the same location codes (and have the same appointment availability) as GOES appointments at the same location. 

However in at least one case (Blaine, WA), there are different location codes for the two appointment types. I have not gone through the entire list, but the list of NEXUS locations is available at: 

https://ttp.cbp.dhs.gov/schedulerapi/locations/?temporary=false&inviteOnly=false&operational=true&serviceName=NEXUS

And the list of GOES locations is at: 

https://ttp.cbp.dhs.gov/schedulerapi/locations/?temporary=false&inviteOnly=false&operational=true&serviceName=Global%20Entry

**Comment by Drewster727** [comment]
@tjd2002 thanks! Are NEXUS/SENTRI/FAST appointments using the same appointment scheduler as GOES? I don't want to add verbiage for that if this tool can't find appointments for those as well. That make sense?

**Comment by tjd2002** [comment]
Check my PR #8; I updated the docs as best I could. 

Thank you for the awesome tool!

**Comment by tjd2002** [comment]
But, short answer. Yes! So your tool is actually useful to anyone looking to make those appointments as well.
